[package]
name = "rs-arrow-array2freq2rbat"
version = "0.1.0"
edition = "2024"

description = "Creates a batch from the frequency of the items in the array."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-arrow-array2freq2rbat"
homepage = "https://github.com/takanoriyanagitani/rs-arrow-array2freq2rbat"
documentation = "https://docs.rs/rs-arrow-array2freq2rbat/latest"
keywords = ["arrow", "frequency", "count", "array"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"

[dependencies.arrow]
version = "56"
default-features = false
features = [
]
